name: move framework tests

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
    branches: ["**"] # glob pattern to allow slash /
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "release**"
      - "main**"

jobs:
  functional-tests:
    runs-on: ubuntu-latest
    steps:
      # NOTE: for debugging CI this allow shell access to github runner. Will print out tmate.io terminal url
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
        timeout-minutes: 15

      - uses: actions/checkout@v3

      # TODO: duplicated with build_env (which is too much of a heavy lift for this workflow)
      - name: install libra cli (for faster Move compiles)
        shell: bash
        run: |
          wget -O $HOME/.cargo/bin/libra https://github.com/0LNetworkCommunity/libra-framework/releases/latest/download/libra
          chmod +x $HOME/.cargo/bin/libra
          ls -l $HOME/.cargo/bin

      # Move framework tests
      - name: move framework
        working-directory: ./framework/libra-framework
        run: libra move test
